Fetter/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from basicapp import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.user_login, name='login'),
    path('index/', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basicapp/', include('basicapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('superAdmin/', views.superAdmin, name='superAdmin'),
    path('instituteAdmin/', views.instituteAdmin, name='instituteAdmin'),
    path('register/', views.superAdmin, name='registerInstituteAdmin'),
    path('instituteAdmin/adduser/', views.addUser, name='adduser'),
    path('index/addNewsFeed/', views.index, name='addnewsfeed'),
    path('index/<int:pk>/', views.NewsFeedDetail.as_view(),name ='detail'),
    path('accountInfo/', views.userAccountInfo, name='accountInfo'),
    path('index/<int:pk>/comment/', views.add_comment_to_post, name = 'add_comment_to_post'),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basicapp/urls.py
from django.urls import path
from django.contrib import admin
from basicapp import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'basicapp'
urlpatterns = [
    path('', views.user_login, name='login'),
    path('instituteAdmin/adduser/', views.adduser, name='adduser'),
    path('accountInfo/', views.userAccountInfo, name='accountInfo'),
    path('addnewsfeed/', views.addNewsFeed, name='addnewsfeed'),
    path('index/', views.index, name='index'),
    path('InstituteProfilePage/', views.instituteprofilepage, name='InstituteProfilePage'),
    path('instituteAdmin/InstituteExtra/', views.InstituteExtra, name='InstituteInfo'),
    path('index/addNewsFeed/', views.instituteAdmin, name='newsfeed'),
    path('InstituteExtra/InstituteSocities/', views.institutesocities, name='InstituteSocities'),
    path('index/<int:pk>/', views.NewsFeedDetail.as_view(), name ='detail'),
    path('index/<int:pk>/comment/', views.add_comment_to_post, name = 'add_comment_to_post'),
    path('index/internships/', views.internships, name = 'internships'),
    path('index/scholarships/', views.scholarships, name = 'scholarships'),
    path('index/programmes/', views.programmes, name = 'programmes'),
    path('index/addUserInterest/', views.addUserInterest, name='addUserInterest'),
    

]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

basicapp/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from basicapp.models import User_Table, Institute, Newsfeed,Comment

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = User_Table
        fields = ('access_type',)

class InstituteProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Institute
        fields = {'institute_name','institute_type', 'director'}

class addUserForm(forms.ModelForm):
    class Meta():
        model = User_Table
        fields = {'institute_name_user',}

class addNewsFeedForm(forms.ModelForm):
    class Meta():
        model = Newsfeed
        fields = {'description', 'news_feed_type','intended_for','image'}

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = {'description',}

basicapp/views.py
from django.shortcuts import render
from django.template import loader

from basicapp.forms import UserForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from basicapp.models import (User_Table, Newsfeed, Institute, Internship,
                            Project, Interest, User_Interest, NewsfeedScore)
from django.db.models import Q
from basicapp.forms import UserForm, UserProfileInfoForm, InstituteProfileInfoForm, addUserForm, addNewsFeedForm, CommentForm
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.csrf import csrf_protect
from django.views.generic import (View, TemplateView,
                                   ListView, DetailView,
                                   CreateView, UpdateView,
                                   DeleteView)


from django.db import connection
from django.shortcuts import redirect
import paralleldots
paralleldots.set_api_key("ghdY3NjkLKVI2uE5i3CK0hkpfWugfO9HATYIX9P8kJc")

# Create your views here.

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

@csrf_exempt
def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                print('Loginned')
                n1 = User_Table.objects.filter(user_name__username__icontains=username)
                print(n1[0].access_type)
            if n1[0].access_type == 'InstituteAdmin':
                return HttpResponseRedirect(reverse('instituteAdmin'))
            elif n1[0].access_type == 'SuperAdmin':
                return HttpResponseRedirect(reverse('superAdmin'))
            elif n1[0].access_type == 'NormalUser':
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print('someone tried login and failed')
            print('username : {} and password {}'.format(username, password))
            return render(request,'basicapp/invalidLogin.html')
    else:
        return render(request, 'basicapp/login.html', {})



@login_required
def index(request):
    n3 = User_Interest.objects.filter(user_name__username__icontains=request.user.username)

    n2= Newsfeed.objects.all()
    interestOne = NewsfeedScore.objects.filter(category=n3[0].interest_name).filter(score__gte=0.85)
    interestTwo = NewsfeedScore.objects.filter(category=n3[1].interest_name).filter(score__gte=0.85)
    interestThree = NewsfeedScore.objects.filter(category=n3[2].interest_name).filter(score__gte=0.85)

    #attempting to make one of all query
    #interestedNewsfeed = NewsfeedScore.objects.filter(Q(category=n3[0].interest_name) | Q(category=n3[1].interest_name) | Q(category=n3[2].interest_name)).filter(score__gte=0.85)
    print(interestOne)


    n1 = User_Table.objects.filter(user_name__username__icontains=request.user.username)
    params = {'user_record': n1, 'first_two_news_feed': n2[0:2], 'interestOneFeed': interestOne,
              'interestTwoFeed': interestTwo,
              'interestThreeFeed': interestThree, 'rest_news_feed': n2[2:]}
    return render(request, 'basicapp/index.html', params)

#@login_required
def instituteAdmin(request):
    n2= Newsfeed.objects.all()
    return render(request, 'basicapp/instituteAdmin.html',{'news_feed':n2,})

@csrf_protect
def superAdmin(request):

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        institute_form = InstituteProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user_name = user

            profile.save()

            institute = institute_form.save(commit=False)
            institute.user_name = user
            institute.save()

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
        institute_form = InstituteProfileInfoForm()

    return render(request, 'basicapp/superAdmin.html', {'user_form':user_form, 'profile_form':profile_form, 'institute_form': institute_form})

def addUser(request):
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        add_user_form = addUserForm(data = request.POST)

        if user_form.is_valid() and add_user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = add_user_form.save(commit=False)
            profile.user_name = user
            profile.access_type = 'NormalUser'
            profile.save()

        else:
            print(user_form.errors, add_user_form.errors)
    else:
        user_form = UserForm()
        add_user_form = addUserForm()

    return render(request, 'basicapp/adduser.html', {'user_form':user_form, 'add_user_form':add_user_form})

def addNewsFeed(request):
    print('here')
    n1 = User_Table.objects.filter(user_name__username__icontains=request.user.username)
    if request.method == 'POST':
       # print('inside POST')
        add_news_feed = addNewsFeedForm(data = request.POST)
        if add_news_feed.is_valid():
            news_feed = add_news_feed.save(commit=False)
            news_feed.user_name = request.user.username
            news_feed.save()

            category = { "Sports":['Cricket', 'Football', 'Soccer', 'Swimming', 'Horse Riding', 'Table Tennis', 'Badminton'], 'Artificial Intelligence':['Machine Learning', 'Deep Learning', 'Mimic', 'Linear Regression', 'Logistic Regression'], 'Internet of Things': ['Automation', 'Alexa', 'Siri', 'Google Home'], 'Data Structure and Algorithms':['DFS', 'BFS', 'Array', 'Stacks', 'Queues', 'Recursion', 'Disjoint Set'], 'Competitive Programming':['Codechef', 'Hackerearth', 'Hackerrank', 'Purple'],
            'Management':['Event', 'Time'], 'Developer':['Software Engineering', 'Project', 'APIs', 'Web Development'], 'Blockchain':['Cryptocurrency', 'Bitcoins', 'Etherium'], 'Operting System':[], 'Art':[], 'Gaming':[], 'Virtual Reality':[], 'Microprocessors':[], 'Aviation':[], 'Mechanical Engineering':[], 'Electronics Engineering':[], 'Textile Engineering':[], 'Mining Engineering':[]}

            api_scores = paralleldots.custom_classifier(request.POST.get('description'), category);
            print(request.POST.get('description'))
            print(api_scores)
            for api_score in api_scores['taxonomy']:
                tag = api_score['tag']
                score = api_score['confidence_score']
                score_table = NewsfeedScore()
                score_table.newsfeed = news_feed
                score_table.category = tag
                score_table.score = score
                score_table.save()

            return index(request)
        else:
            print(news_feed.errors)
    else:
        add_news_feed_form = addNewsFeedForm()

    print('here after')
    return render(request, 'basicapp/addnewsfeed.html', {'add_news_feed_form':add_news_feed_form,'user_record':n1})

#will do later for handling interest of user inputted by user itself
# added on 24_DEC
@csrf_exempt
def addUserInterest(request):
    template = loader.get_template('basicapp/addUserInterest.html')
    if request.method == 'GET':
        return HttpResponse(template.render())
    else:
        input_username = User.objects.get(id=request.user.id)
        input_interest = request.POST.get('user_interest')
        user_interest = User_Interest()
        user_interest.user_name = input_username
        user_interest.interest_name = input_interest
        user_interest.save()
        return HttpResponse("interest added")

class NewsFeedDetail(DetailView):
    context_object_name= 'newsfeed_detail'
    model=Newsfeed
    template_name= 'basicapp/feed_details.html'
@login_required
def userAccountInfo(request):
    n1 = Internship.objects.filter(user_name__username__icontains = request.user.username)
    n2 = Project.objects.filter(user_name__username__icontains = request.user.username)
    n3 = User_Interest.objects.filter(user_name__username__icontains = request.user.username)
    n4 = User_Table.objects.filter(user_name__username__icontains = request.user.username)
    return render(request, 'basicapp/UserProfilePage.html', {'internships': n1, 'projects': n2, 'interests': n3, 'User': n4})

@login_required
def instituteprofilepage(request):
    return render(request, 'basicapp/InstituteProfilePage.html')

@login_required
def InstituteExtra(request):
    return render(request, 'basicapp/InstituteExtras.html')


@login_required
def institutesocities(request):
    return render(request, 'basicapp/InstituteSocities.html')

@login_required
def internships(request):
    feed=Newsfeed.objects.filter(news_feed_type__exact = 'internship')
    return render(request, 'basicapp/UserExtras.html', {'feed':feed})
@login_required
def scholarships(request):
    feed=Newsfeed.objects.filter(news_feed_type__exact = 'scholarship')
    return render(request, 'basicapp/UserExtras.html', {'feed':feed})
@login_required
def programmes(request):
    feed = Newsfeed.objects.filter(news_feed_type__exact = 'programmes')
    return render(request, 'basicapp/UserExtras.html', {'feed':feed})
@login_required
def add_comment_to_post(request, pk):
    post = Newsfeed.objects.get(pk = pk)
    if request.method == "POST":

basicapp/templates/basicapp/UserExtras.html
{% load static %}
<html>
<title>User Extras</title>
<link href="{% static 'css/UserExtras.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/UserExtras.js' %}"></script>

	<body style="background-color: WhiteSmoke;padding:0px;">

		<!-- NavBar -->
		<nav class="navbarBody">
			<span style="color: white">Fetter</span>
			<ul class="listBody">
				<li class="list">
					<a href="{% url 'index' %}"><button class="navbarButton">
						<img src="{% static 'Images/home3.png' %}" class="navBarIcon">
						<br>
						Home
					</button></a>
				</li>

				<li class="list">
					<button class="navbarButton" onclick="loadRightVerticalNavbar()">
						<img src="{% static 'Images/message1.png' %}" class="navBarIcon">
						<br>
						Messages
					</button>
				</li>
				<li class="list">
					<button class="navbarButton" onclick="loadRightVerticalNavbar()">
						<img src="{% static 'Images/notification1.png' %}" class="navBarIcon">
						<br>
						Notifications
					</button>
				</li>
			</ul>
			<!--NavBar Right Section -->
			<div class="navBarRight">
				<!-- Profile Icon -->

				<!-- Profile Icon ends -->
				<a href="{% url 'basicapp:accountInfo' %}"><button class="navBarAccount">
					Account
				</button></a>
				<a href="{% url 'logout' %}"><button class="navBarlogoutButton">
					Logout
				</button></a>
			</div>
			<!-- NavBar Right Section ends -->
		</nav>

		<!-- NavBar ends -->

		<!-- Container (Envelope) -->
		<div class="myContainer">
			<!-- Left Section -->
		<div class="left" style="visibility:hidden">
			<!-- Profile Card -->
			<br>
			<center>
			<div class="profileBlock">

				<!-- Blue Color -->
				<div style="width:100%;height:70px;background-color: lightblue;">

				</div>
				<!-- Blue Color ends -->
				<center>
					<div class="profileImageBlock">
						<img src="{% static 'Images/dp.jpg' %}" class="profileImage">
					</div>
					<br>
					<div class="profileBlockUsername">
						Harry Chhabra
					</div>
					<div class="profileBlockInstituteName">
						Student at Dr. B.R. Ambedkar National Institute of Technology, Jalandhar
					</div>
					<hr>
					<div class="profileBlockOtherDetails">
						harrychhabra1998@gmail.com
					</div>
				</center>
			</div>
			<!-- Profile Card end -->
		</center>
			<hr>
			<!-- Other Contents -->
			<center>
			<div class="leftContentsBlock">
				<ul style="list-style-type: none;padding-left: 0px;border:1px solid black;">
					<a href="{% url 'basicapp:internships' %}"><li class="leftContent">
						Internships
					</li></a>
					<a href="{% url 'basicapp:scholarships' %}"><li class="leftContent">
						Scholarship
					</li></a>
					<a href="{% url 'basicapp:programmes' %}"><li class="leftContent">
						Programmes
					</li></a>
				</ul>
			</div>
		</center>
			<!-- Other Contents ends -->
		</div>
		<!-- Left Section Ends -->

		<!-- Middle Section -->
		<div class="middle">
			<ul style="list-style-type: none;padding-left: 0px;padding:2px;">
				<br>
				<!-- NewsFeed Update -->
				<li>
					<div style="width:100%;padding:5px;border: 0px solid black;background-color: white;box-shadow: 0px 0px 0px 0px;">
						<br>
						{% for feed in feed %}

						<h4>{{ feed.user_name }}</h4>
						<p>{{ feed.date }}</p>
						<p>{{ feed.description }}</p>
						<hr>
						{% empty %}
						<p>No posts there</p>
						{% endfor %}
					</div>
					<br>
				</li>
				<!-- NewsFeed Update ends -->
		</div>
		<!-- Middle Section ends -->

		<!-- Right Section -->
		<div class="right" style="visibility:hidden">
			<br>
			<div class="rightContent">
				<!-- Search Bar -->
			<div class="rightSearchBlock">
				<input type="text" placeholder="Search Username" id="rightSearchBlockInputId" class="rightSearchBlockInput">
				<button class="rightSearchBlockButton">
					<img src="{% static 'Images/search1.png' %}" style="width:100%;height: 100%;">
				</button>
			</div>
			<br><br>
			<!-- Search bar ends -->
			<!-- Notification Block -->
			<div class="rightNotificationBlock" style="display:none;">
				<div class="rightNotificationBlockHeader">
					Notifications:
				</div>
				<ul style="list-style-type: none;padding-left: 2px;height: 100%;overflow: scroll">
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
					<li class="notificationBlockLi">
						<span class="notificationBlockUploadBy">Nitish Kumar</span> posted of Machine Learing</span> interest.
					</li>
				</ul>
			</div>
			<!-- Notification Block ends -->




			</div>
		</div>
		<!-- Right Section ends -->

		<!-- Right Section Overlapping 1 -->
		<div class="overlappingBlock">
			<div class="overlappingBlockContent" style="display:none;">
				<div class="overlappingBlockHeader" onclick="closeRightVerticalNavbar()">
					Back
				</div>

			</div>

		</div>
		<!-- Right Section Overlapping 1 ends -->
		</div>
		<!-- Container (Envelope) ends -->

	</body>

</html>

basicapp/templates/basicapp/add_comment_to_post.html
{% extends 'basicapp/base.html' %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  {% block body_block %}
    <form  method="POST">
        {% csrf_token %}
      {{ form.as_p }}
      <button type="submit"> Comment </button>
    </form>
  {% endblock %}
</html>

basicapp/templates/basicapp/adduser.html
{% extends "basicapp/base.html" %}
  {% block body_block %}
  {% load static %}
<div class="jumbotron">
  <form method="POST">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ add_user_form.as_p }}
    <input type="submit" value="adduser">
  </form>
</div>



  {% endblock %}

basicapp/templates/basicapp/instituteAdmin.html
  {% load static %}

  <html>
  <title>Institute Admin</title>
  <link href="{% static 'css/InstituteAdmin.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet">
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/InstituteAdmin.js' %}"></script>

  	<body style="background-color: WhiteSmoke;padding:0px;">
      <!-- NavBar -->
      <nav class="navbarBody">
        <ul class="listBody">
          <li class="list" style="width:auto;padding-right:20%;">
            <span style="color: white;font-size:3em;">Fetter</span>
            <!-- <span style="padding-right:30%;display:inline-block;border:1px solid red"></span> -->
          </li>
          <li class="list">
            <button class="navbarButton">
              <img src="{% static 'Images/maleIcon.png' %}" class="navBarIcon">
              <br>
              Home
            </button>
          </li>

          <li class="list" style="visibility:hidden">
            <button class="navbarButton" onclick="loadRightVerticalNavbar()">
              <img src="{% static 'Images/message1.png' %}" class="navBarIcon">
              <br>
              Messages
            </button>
          </li>
          <li class="list" style="visibility:hidden">
            <button class="navbarButton" onclick="loadRightVerticalNavbar()">
              <img src="{% static 'Images/notification1.png' %}" class="navBarIcon">
              <br>
              Notifications
            </button>
          </li>
          </ul>
          <ul class="listBody" style="border:0px solid red;width:24%;height:auto;margin:0px;padding:0px;">
          <li class="list" style="float:right;height:100%">
            <a href="{% url 'basicapp:InstituteProfilePage' %}">
              <button class="navBarAccount">
              Account
            </button></a>
          </li>
          <li class="list" style="float:right">
            <a href="http://127.0.0.1:8000/"><button class="navBarlogoutButton">
              Logout
            </button></a>
          </li>
            <!--NavBar Right Section -->
          </ul>
        </nav>
  		<!-- Container (Envelope) -->
  		<div class="myContainer">
  			<!-- Left Section -->
  		<div class="left">
  			<!-- Profile Card -->
  			<br>
        <br>
  			<center>
  			<div class="profileBlock">

          <!-- Blue Color -->
  				<div style="width:100%;height:25%;background-color: lightblue;">

  				</div>
  				<!-- Blue Color ends -->
  				<center>
  					<div class="profileImageBlock">
  						<img src="{% static 'Images/maleIcon.png' %}" class="profileImage">
  					</div>
  					<br>
  					<div class="profileBlockUsername">
  						Dr. B.R. Ambedkar National Institute of Technology
  					</div>
  					<div class="profileBlockInstituteName">
  						Director: Nitish Kumar
  					</div>
  					<hr>
  					<div class="profileBlockOtherDetails">
  						director@nitj.ac.in
  					</div>
  				</center>
  			</div>
  			<!-- Profile Card end -->
  		</center>
  			<hr>
        <br>


        <!-- Other Contents -->
        <center>
        <div class="leftContentsBlock">
          <ul style="list-style-type: none;padding-left: 0px;border:0px solid black;">
            <a href="{% url 'basicapp:InstituteInfo' %}"><li class="leftContent">
              <button class="leftContent" style="width:100%;">Internships</button>
            </li></a>
            <a href="{% url 'basicapp:InstituteInfo' %}"><li class="leftContent">
              <button class="leftContent" style="width:100%;">Scholarship</button>
            </li></a>
            <a href="{% url 'basicapp:InstituteInfo' %}"><li class="leftContent">
              <button class="leftContent" style="width:100%;">Programmes</button>
            </li></a>
            <a href="{% url 'basicapp:adduser' %}"><li class="leftContent">
              <button class="leftContent" style="width:100%;">Add User</button>
        </li>
          </a>
          </ul>
        </div>
      </center>
        <!-- Other Contents ends -->


  		</div>
  		<!-- Left Section Ends -->

      <!-- Middle Section -->
      <div class="middle" style="margin:0px;">
        <ul style="list-style-type: none;padding-left: 0px;padding:2px;">
          <br>
          <!-- NewsFeed Update -->
          <li>
            <div style="width:100%;padding:15px;border: 0px solid black;background-color: white;box-shadow: 0px 0px 0px 0px;">
              <a href="{% url 'basicapp:newsfeed' %}">
                <button style="width:100%;border:1px solid black;">Add Status</button>
              </a>
            </div>
            <br>
          </li>
          <!-- NewsFeed Update ends -->
          {% for feed in news_feed %}
            <li>
            <div class="newsfeedContent">
              <div class="contentHeader">
                <!-- Profile Pic, username, Institue name -->
                <div class="newsfeedUserDetail" style="width:100%;background-color:lightblue">
                  <div class="newsfeedUploadedByImage">
                    <img src="{% static 'Images/maleIcon.png' %}" style="width:70px;height: 70px;">
                  </div>
                  <span class="newsfeedUploadedBy">
                    {{ feed.user_name }}
                  <br>
                </span>
                  <span class="newsfeedUploadedByInstituteName">
                    {{ feed.news_feed_type }}
                  </span>
                  <br>
                  <span class="newsfeedContentUploadDate">
                    {{ feed.date }}
                  </span>
                </div>
              </div>
              <br>
              <!-- Uploaded Image -->
              <div class="newsfeedUploadedImageBlock" style="display:none">
                <img src="{% static 'Images/back6.jpg' %}" class="newsfeedUploadedImage">
              </div>
              <!-- Uploaded Image ends -->
              <!--   Caption -->
              <div class="newsfeedContentCaptionBlock">
      <pre class="newsfeedContentCaption">
      {{ feed.description }}
      </pre>
              </div>
              <br>
              <!-- Caption ends -->
            </div>
          </li>
          <br>
            {% endfor %}

        </ul>
        <!-- Load More -->
        <div class="loadMoreBlock">
          Load more stories
        </div>
        <!-- Load More ends -->
      </div>
      <!-- Middle Section ends -->
  		<!-- Right Section -->

  		<div class="right">
  			<br>
  			<div class="rightContent">
  				<!-- Search Bar -->
  			<div class="rightSearchBlock">
  				<input type="text" placeholder="Search Username" id="rightSearchBlockInputId" class="rightSearchBlockInput">
  				<button class="rightSearchBlockButton">
  					<img src="{% static 'Images/search1.png' %}" style="width:100%;height: 100%;">
  				</button>
  			</div>
  			<br><br>
  			<!-- Search bar ends -->

  			</div>
  		</div>
  		<!-- Right Section ends -->

  		</div>
  		<!-- Container (Envelope) ends -->

  	</body>

  </html>